spring:
  application:
    name: order-api
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/orderdb?useSSL=false
    username: orderdb
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 14400
  cors:
    allowed-origins: http://localhost:5173

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

server:
  shutdown: graceful
